name: C/C++ CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build wpy+
        working-directory: interpilers/wpy+
        run: make
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: wpy-binary   # 👈 consistent name
          path: interpilers/wpy+/wpy+

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: wpy-binary   # 👈 must match exactly
          path: interpilers/wpy+
      - name: Run hello.pyp
        working-directory: interpilers/wpy+
        run: |
          chmod +x wpy+
          ./wpy+ hello.pyp
